import { useMemo, useState } from 'react'
import { products, sets, formatPrice, getProductById, getShipping } from '../data/content'
import { whatsappUrl } from '../data/config'
import { useShop } from '../store/ShopContext'
import { buildWhatsAppMessage, createOrderId } from '../utils/order'
const emptyCustomer = { name: '', phone: '', province: '', city: '', address: '', notes: '' }

function cartRows(cart, lineKey) { return cart.map(line => { if (line.type === 'set') { const set = sets.find(item => item.id === line.setId); const items = line.items.map(item => ({ ...item, product: getProductById(item.productId) })); const variant = items[0]?.product.variants.find(item => item.colorId === line.colorId); return { ...line, key: lineKey(line), name: set?.name ?? 'Set', image: variant?.images[0], items, unitPrice: set?.price.launch ?? null, colorLabel: variant?.colorName ?? line.colorId } } const product = products.find(item => item.id === line.productId); const variant = product?.variants.find(item => item.colorId === line.colorId); return { ...line, key: lineKey(line), name: product?.name ?? 'Producto', image: variant?.images[0], product, variant, unitPrice: product?.price.launch ?? null, colorLabel: variant?.colorName ?? line.colorId } }).filter(Boolean) }

export default function CartDrawer() {
  const { cart, updateQuantity, removeLine, clearCart, isCartOpen, setCartOpen, lineKey, notice, setNotice } = useShop(); const [showForm, setShowForm] = useState(false); const [customer, setCustomer] = useState(emptyCustomer); const [error, setError] = useState('')
  const rows = useMemo(() => cartRows(cart, lineKey), [cart, lineKey]); const hasPendingPrice = rows.some(row => row.unitPrice == null); const subtotal = rows.reduce((sum, row) => sum + (row.unitPrice ?? 0) * row.quantity, 0); const shipping = getShipping(customer.city)
  const validate = () => { if (!customer.name.trim() || !customer.province.trim() || !customer.city.trim() || !customer.address.trim()) return 'Completa nombre, provincia, cantón y dirección.'; if (!/^\+?[0-9\s-]{8,16}$/.test(customer.phone)) return 'Ingresa un teléfono válido.'; return '' }
  const checkout = event => { event.preventDefault(); const issue = validate(); if (issue) return setError(issue); const message = buildWhatsAppMessage({ id: createOrderId(), customer, rows, subtotal }); window.open(whatsappUrl(message), '_blank', 'noopener,noreferrer'); setError('') }
  const updateField = event => setCustomer(current => ({ ...current, [event.target.name]: event.target.value }))
  return <><div className={isCartOpen ? 'drawer-backdrop open' : 'drawer-backdrop'} onClick={() => setCartOpen(false)}></div><aside className={isCartOpen ? 'cart-drawer open' : 'cart-drawer'} aria-hidden={!isCartOpen}><header><h2>TU CARRITO / {cart.reduce((sum, item) => sum + item.quantity, 0)}</h2><button onClick={() => setCartOpen(false)} aria-label="Cerrar carrito">×</button></header>{notice && <p className="cart-notice">{notice}<button onClick={() => setNotice('')} aria-label="Cerrar aviso">×</button></p>}<div className="cart-lines">{rows.length ? rows.map(row => <article className="cart-line" key={row.key}>{row.image ? <img src={row.image} alt=""/> : <div className="cart-image-pending">KREA</div>}<div><h3>{row.name}</h3><p>{row.colorLabel}</p>{row.type === 'set' ? row.items.map(item => <p key={item.productId}>{item.product.name}: {item.size}</p>) : <p>Talla: {row.size}</p>}<p>{row.unitPrice == null ? 'PRECIO POR CONFIRMAR' : formatPrice(row.unitPrice)}</p><div className="quantity"><button onClick={() => updateQuantity(row.key, row.quantity - 1)} aria-label="Reducir cantidad">−</button><span>{row.quantity}</span><button onClick={() => updateQuantity(row.key, row.quantity + 1)} aria-label="Aumentar cantidad">+</button></div></div><button className="remove" onClick={() => removeLine(row.key)} aria-label={`Eliminar ${row.name}`}>ELIMINAR</button></article>) : <div className="empty-cart"><p>No tienes productos todavía.</p><a className="button" href="/collections/pastel-dolly" onClick={() => setCartOpen(false)}>VER PASTEL DOLLY</a></div>}{showForm && rows.length > 0 && <form className="checkout-form" onSubmit={checkout}><h3>DETALLES DE ENTREGA</h3>{[['name', 'Nombre completo'], ['phone', 'Teléfono'], ['province', 'Provincia'], ['city', 'Cantón / Ciudad'], ['address', 'Dirección o punto de referencia']].map(([name, label]) => <label key={name}>{label}<input name={name} value={customer[name]} onChange={updateField} required /></label>)}<label>Notas del pedido <textarea name="notes" value={customer.notes} onChange={updateField}/></label><p className="shipping-preview">Envío: <b>{shipping.label}</b><br />{shipping.detail}</p>{error && <p className="form-error">{error}</p>}<button className="add-button" type="submit">FINALIZAR POR WHATSAPP</button></form>}</div><footer><p>Envío gratuito en todo Grecia.</p><p className="shipping-note">Para otras ubicaciones de Costa Rica se añadirá el costo de envío correspondiente.</p><div><span>SUBTOTAL</span><b>{hasPendingPrice ? 'POR CONFIRMAR' : formatPrice(subtotal)}</b></div>{rows.length > 0 && !showForm && <button className="add-button" onClick={() => setShowForm(true)}>FINALIZAR PEDIDO POR WHATSAPP</button>}{rows.length > 0 && <button className="clear-cart" onClick={clearCart}>VACIAR CARRITO</button>}<small>Te confirmaremos disponibilidad, envío y entrega directamente por WhatsApp.</small></footer></aside></>
}
